# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# Should be run after running and pushing results from scripts/bump_versions.json
name: Publish
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
  
      - name: Safety Check
        id: check
        run: |
          LAUNCHER_VERSION=$(jq -r '.version' packages/obsidian-launcher/package.json)
          SERVICE_VERSION=$(jq -r '.version' packages/wdio-obsidian-service/package.json)
          REGISTRY_VERSION=$(npm view wdio-obsidian-service version)
          if [[ "$LAUNCHER_VERSION" != "$SERVICE_VERSION" ]]; then
            echo "package versions must match"
            exit 1
          fi
          if [[ "$REGISTRY_VERSION" == "$SERVICE_VERSION" ]]; then
            echo "version already published"
            exit 1
          fi
          echo "version=$SERVICE_VERSION" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Release
        run: |
          VERSION="${{ steps.check.outputs.version }}"
          gh release create "VERSION" --title "VERSION"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Publish
        run: npm publish --workspaces --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Generate docs
        run: npm run doc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: docs
          clean: true
          commit-message: "Publish docs for version ${{ steps.check.outputs.version }}"
