# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# Trigger this workflow with `pnpm run release patch`
name: Publish
on:
  push:
    tags: ["*.*.*"]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with: # Needed for the `--notes-from-tag` option to work
          fetch-depth: 0
          ref: ${{ github.ref }}

      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Build
        run: |
          pnpm install --frozen-lockfile
          pnpm run --aggregate-output --reporter-hide-prefix build

      - name: Github Release
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          gh release create "$VERSION" --title="$VERSION" --verify-tag --notes-from-tag $RELEASE_TYPE
        env:
          RELEASE_TYPE: ${{ contains(github.ref, '-') && '--prerelease' || ''}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: pnpm publish -r --aggregate-output --no-git-checks --tag $RELEASE_TYPE
        env:
          RELEASE_TYPE: ${{ contains(github.ref, '-') && 'beta' || 'latest'}}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Generate docs
        run: pnpm run doc

      - name: Upload docs as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: generated-docs/

  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-publish
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
