# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  actions: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  pre-check: # Check and avoid running tests on the same code (e.g. after pr merge)
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          paths_ignore: '["**/*.md"]'
          cancel_others: 'true'
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["workflow_dispatch"]'

  # Test build, lint & unit before running expensive e2e tests
  test-unit:
    needs: [pre-check]
    if: ${{ needs.pre-check.outputs.should_skip != 'true' }}
    name: "test build, lint & unit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run --aggregate-output --reporter-hide-prefix build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          retention-days: 1
          path: | # Workaround, see https://github.com/actions/upload-artifact/issues/174#issuecomment-2878874192
            root-placeholder
            packages/*/dist

  test-e2e-desktop:
    needs: [test-unit]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            node-version: "24.x"
            test-level: "standard"
            obsidian-versions: "latest/latest/standard"
            package-resolution: highest
          - os: ubuntu-latest
            node-version: "24.x"
            test-level: "standard"
            obsidian-versions: "latest/latest/standard"
            package-resolution: highest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    name: "test e2e (${{ matrix.os }}, node ${{ matrix.node-version }} obsidian: ${{ matrix.obsidian-versions }}, package-resolution: ${{ matrix.package-resolution }})"
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # cache: 'pnpm'

      # - name: Cache .obsidian-cache
      #   uses: actions/cache@v4
      #   with:
      #     path: .obsidian-cache
      #     key: obsidian-cache-${{ matrix.os }}-${{ matrix.obsidian-versions }}-${{ hashFiles('./obsidian-versions.json') }}

      - shell: bash
        run: |
          if [[ '${{ matrix.package-resolution }}' == 'highest' ]]; then
            rm -rf pnpm-lock.yaml node_modules packages/*/node_modules
            pnpm install --config.resolutionMode=highest --no-frozen-lockfile
          elif [[ '${{ matrix.package-resolution }}' == 'lowest-direct' ]]; then
            rm -rf pnpm-lock.yaml node_modules packages/*/node_modules
            pnpm install --config.resolutionMode=lowest-direct --no-frozen-lockfile
          else
            pnpm install --frozen-lockfile
          fi

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build

      # We already ran these, but we'll run in the matrix as well to test different node versions
      - name: Run unit tests
        run: pnpm run --aggregate-output --reporter-hide-prefix test:unit

      # On linux runners we need to set up a virtual graphics stack for Obsidian. Here we use xvfb as a virtual display
      # server and herbstluftwm as the window manager. (You can sometimes get by without the window manager, but some
      # Obsidian features won't work properly wihtout it.)
      - if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        name: "Setup virtual graphics"
        run: |
            # Some hacks to speed up apt install
            sudo rm -rf /etc/apt/sources.list.d/*.list
            echo "set man-db/auto-update false" | sudo debconf-communicate
            sudo dpkg-reconfigure man-db

            sudo apt-get update -q
            sudo apt-get install -q herbstluftwm dzen2 x11-xserver-utils

            export DISPLAY=:99
            echo "DISPLAY=$DISPLAY" >> "$GITHUB_ENV"
            Xvfb $DISPLAY -screen 0 1280x1024x24 +extension GLX -noreset &
            sleep 1
            herbstluftwm &
            sleep 1

      - name: Run e2e tests
        run: pnpm run ${{ matrix.pnpm-args }} --sequential -F wdio-obsidian-service test:e2e:standalone
        env:
          # 3 test levels:
          #   - basic (fast, just test the core features)
          #   - standard (medium, run most the tests)
          #   - all (slow, include the expensive tests)
          TEST_LEVEL: ${{ matrix.test-level }}
          OBSIDIAN_VERSIONS: ${{matrix.obsidian-versions}}
          WDIO_MAX_INSTANCES: ${{matrix.max-instances || '3'}}
          # Secrets won't be available when run on a PR
          OBSIDIAN_EMAIL: ${{ secrets.OBSIDIAN_EMAIL }}
          OBSIDIAN_PASSWORD: ${{ secrets.OBSIDIAN_PASSWORD }}

  post-check:
    if: always()
    needs: [test-unit, test-e2e-desktop]
    runs-on: ubuntu-latest
    steps:
      - name: Check all tests passed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
          allowed-skips: ${{ toJSON(needs) }}
