# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Update Obsidian Versions
on:
  schedule: # Run every 8 hours at minute 22
    - cron: '22 */8 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  update-obsidian-versions:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: "Check if update is needed"
        id: check
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            // Get the latest commit to desktop-releases.json
            const commitResponse = await github.rest.repos.listCommits({
                owner: "obsidianmd", repo: "obsidian-releases",
                path: "desktop-releases.json", per_page: 1,
            })
            const latestCommit = commitResponse.data[0].sha;
            const obsidianVersionsUrl = `https://raw.githubusercontent.com/${context.repo.owner}/${context.repo.repo}/HEAD/obsidian-versions.json`;
            const versionsJson = await fetch(obsidianVersionsUrl).then(r => r.json());

            const ourLatestCommit = versionsJson.metadata.commitSha;
            const ourLatestTimestamp = new Date(versionsJson.metadata.timestamp);

            if (!latestCommit || !ourLatestCommit || isNaN(ourLatestTimestamp.getTime())) {
                throw Error("Failed to parse requests");
            }

            const now = new Date();
            const timeSinceLastUpdate = (now.getTime() - ourLatestTimestamp.getTime()) / 1000; // convert to seconds
            const needsUpdate = (
                // if obsidian the desktop-releases.json file has changed
                latestCommit != ourLatestCommit ||
                // trigger every once in a while even if there are no Obsidian updates. GitHub disables schedule
                // workflows after 60 days of repo "inactivity". update-obsidian-versions will add a commit if it's been
                // 30 days since the last Obsidian update to keep the repository "active". Running the script will also
                // let it catch re-uploads of Obsidian assets or anything like that.
                timeSinceLastUpdate >= 30 * 24 * 60 * 60 ||
                // The desktop-releases.json can be updated a bit before the GitHub release is actually created, which
                // could cause in obsidian-versions.json to be incomplete. So we'll re-run for a bit after an update to
                // make sure we catch any changes to it
                timeSinceLastUpdate <= 24 * 60 * 60
            );
            return needsUpdate ? 'true' : 'false';

      - if: ${{ steps.check.outputs.result == 'true' }}
        uses: actions/checkout@v4
        with:
          # By default, GitHub won't trigger workflows from events created from a workflow, so the new commit won't
          # trigger the tests. The recommended workaround is to use a Personal Access Token instead of the default
          # GITHUB_TOKEN. Using the PAT also lets the workflow bypass branch protection (if the user is allowed to).
          # See
          # - https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflow
          # - https://stackoverflow.com/questions/67550727 
          token: ${{ secrets.GH_PAT }}
      - if: ${{ steps.check.outputs.result == 'true' }}
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - if: ${{ steps.check.outputs.result == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - if: ${{ steps.check.outputs.result == 'true' }}
        name: "Update obsidian-versions.json"
        run: |
          pnpm install --frozen-lockfile
          cd packages/obsidian-launcher
          pnpm run build
          npx obsidian-launcher update-version-list --max-instances 4 ../../obsidian-versions.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ steps.check.outputs.result == 'true' }}
        name: Commit
        run: |
          git config --global user.name '${{github.repository_owner}}'
          git config --global user.email '${{github.repository_owner}}@users.noreply.github.com'
          if [[ $(git diff -- obsidian-versions.json) ]]; then
            git pull
            git add obsidian-versions.json
            git commit -m "Bot: update obsidian-versions.json"
            git push
          else
            echo "No change to obsidian-versions.json"
          fi
